### ISSUE TITLE
Support ssh url as destination

### ISSUE THREAD

**Issue by cybertk** [cybertk/git-copy#5]
`git copy git-copy git@github.com:cybertk/git-copy.git `

```
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:867:in `scheme=': Invalid scheme format: git@github.com (Addressable::URI::InvalidURIError)
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:795:in `block in initialize'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:2302:in `call'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:2302:in `defer_validation'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:792:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:135:in `new'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/addressable-2.4.0/lib/addressable/uri.rb:135:in `parse'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-copy-0.2.1/lib/git-copy.rb:12:in `copy'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-copy-0.2.1/bin/git-copy:30:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.3/bin/git-copy:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.3/bin/git-copy:23:in `<main>'
```

**Comment by cybertk** [comment]
`git remote add mirror git-copy git@github.com:cybertk/git-copy.git` then `git push --mirror` works fine.
